package com.silbury.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 15 11:53:39 IST 2016
// ---------------------------------------------------------------------
public interface iDashBoardAm extends ApplicationModule {
    void executeSearchVo(String region, String country, String location);
}

